---
# This role adds a first user to the system

- name: "Users group"
  group:
    name: users
    state: present

- name: "First user"
  user:
    name: {{ first-user.username }}
    comment: {{ first-user.comment }}
    group: users
    shell: "/bin/bash"
    generate_ssh_key: yes
    append: yes
    groups:
      - wheel # we make the first user an admin of the system

- name: "Bash prompt"
  lineinfile:
    path: "/home/{{ first-user.username }}/.bashrc"
    regexp: '^export PS1='
    line: 'export PS1="{{ first-user.prompt }}"'
    #line: 'export PS1="\[\033[38;5;39m\][\t]\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]\[\033[38;5;2m\]\u\[$(tput sgr0)\]\[\033[38;5;13m\]@\H\[$(tput sgr0)\]\[\033[38;5;15m\]:\W> \[$(tput sgr0)\]"'

- name: "Sudoer without password"
  lineinfile:
    dest: "/etc/sudoers.d/{{ first-user.username }}"
    state: present
    create: yes
    regexp: '^{{ first-user.username }} ALL='
    line: '{{ first-user.username }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
